# Site settings
title: John Fabry
#email: john@mads.ninja
description: > # this means to ignore newlines until "baseurl:"
  Random musings and ramblings of a geek and sysadmin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://johnfabry.azurewebsites.net" # the base hostname & protocol for your site
twitter_username: ConsoleAccess
github_username: JFFail
#destination: /var/www/mads.ninja/public_html
paginate: 10

# Build settings
markdown: kramdown
